//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RockIRCXRA.rc
//
#define IDC_MYICON                      2
#define IDS_APP_TITLE                   3
#define IDD_ABOUTBOX                    4
#define IDC_ROCKIRCXRA                  5
#define IDI_ROCKIRCXRA                  6
#define IDD_DIALOG1                     7
#define IDD_ABOUT                       8
#define IDR_MAINFRAME                   9
#define IDD_EXCEPTION                   10
#define IDD_EXCEPTIONDIALOG             11
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_SMALL                       108
#define IDC_ROCKIRCX                    109
#define IDD_STATUS                      130
#define IDD_MAIN                        131
#define IDD_IOCTL                       132
#define IDD_TECH                        133
#define IDD_GENERAL                     134
#define IDD_GENERALSETTINGS             135
#define IDD_GENERALMOTD                 136
#define IDB_UNDERLINE                   137
#define IDB_ADD                         138
#define IDB_BOLD                        139
#define IDB_DELETE                      140
#define IDB_MODIFY                      141
#define IDB_LOAD                        142
#define IDB_REFRESH                     143
#define IDB_SAVE                        144
#define IDD_ACCTS                       145
#define IDD_BANS                        146
#define IDD_CHANNEL                     148
#define IDD_USER                        151
#define IDD_SERVERS                     152
#define IDD_SECURITY                    153
#define IDD_FILTER                      154
#define IDD_ADDBINDING                  156
#define IDD_ACCTDIALOG                  157
#define IDD_FILTERDIALOG                158
#define IDD_BANDIALOG                   159
#define IDD_INBOUND                     161
#define IDD_SERVERDETAIL                161
#define IDD_SPOOFDETECTED               163
#define IDD_SPOOFEDDETAILS              164
#define IDD_SPOOFEDEXPORT               165
#define IDD_SPOOFEDREPORT               166
#define IDD_REGCHANNEL                  167
#define IDD_REGCHANGENERAL              168
#define IDD_REGCHANACCESS               169
#define IDD_REGCHANMODES                170
#define IDD_ACCESS                      171
#define IDB_FOLDER                      172
#define IDD_CONNECT                     173
#define IDD_RAPASSWORD                  174
#define IDB_WARNING                     175
#define IDB_ERROR                       176
#define IDB_INFO                        177
#define IDB_OK                          178
#define IDC_VSMAXNICKLEN                1000
#define IDC_EDITACCTUSERNAME            1001
#define IDC_BTNREFRESHBANS              1002
#define IDC_EDITFILTER                  1003
#define IDC_EDITFILTERNICK              1004
#define IDC_EDITFILTERCHAN              1005
#define IDC_CBSERVERACTION              1006
#define IDC_EDITLOC1                    1007
#define IDC_EDITMAXNICKLEN              1008
#define IDC_TREE                        1009
#define IDC_BOX                         1010
#define IDC_BTNMODBINDING               1011
#define IDC_EDITUMSENDQ                 1012
#define IDC_EDITNICKDELAY               1013
#define IDC_EDITMSGDELAY                1014
#define IDC_TXTDCDMLIMIT                1015
#define IDC_EDITFILTEROK                1016
#define IDC_LVREPORT                    1017
#define IDC_BTNCLEAR                    1018
#define IDC_BTNREPORT                   1019
#define IDC_TABGENERAL                  1020
#define IDC_TXTCDMLIMIT                 1021
#define IDC_LISTFILTERNICK              1022
#define IDC_CKFILTER                    1023
#define IDC_CKCSQUITSASPARTS            1024
#define IDC_CBCACHEDNS                  1025
#define IDC_EDITCACHEDNS                1026
#define IDC_CKSPOOF                     1027
#define IDC_RDMASK1                     1028
#define IDC_EDITMOTD                    1029
#define IDC_BTNMOTDLOAD                 1030
#define IDC_BTNMOTDSAVE                 1031
#define IDC_CBMOTDCOLOR                 1032
#define IDC_BTNMOTDBOLD                 1033
#define IDC_BTNMOTDUNDERLINE            1034
#define IDC_EDITCANCEL                  1035
#define IDC_LVACCTS                     1036
#define IDC_TABACCTS                    1037
#define IDC_TABBANS                     1038
#define IDC_LVBANS                      1039
#define IDC_CKSPOOF23                   1040
#define IDC_CKSPOOF80                   1041
#define IDC_CKSPOOF1080                 1042
#define IDC_VSCCMAXCHANS                1043
#define IDC_LVREGCHAN                   1044
#define IDC_VSCSMAXACCESS               1045
#define IDC_TABSERVERS                  1046
#define IDC_GRPINBOUND                  1047
#define IDC_GRPOUTBOUND                 1048
#define IDC_LVINBOUND                   1049
#define IDC_VSMSGDELAY                  1050
#define IDC_BTNFILTEROK                 1051
#define IDC_TXTLOCALUSERS               1052
#define IDC_TXTGLOBALUSERS              1053
#define IDC_EDITSTATUS                  1054
#define IDC_EDITUPTIME                  1055
#define IDC_TXTADMINS                   1056
#define IDC_TXTIRCOPS                   1057
#define IDC_TXTPOWERUSERS               1058
#define IDC_TXTDYNLOCAL                 1059
#define IDC_TXTDYNGLOBAL                1060
#define IDC_TXTREGLOCAL                 1061
#define IDC_txtREGGLOBAL                1062
#define IDC_BTNSERVERACTION             1063
#define IDC_TXTSERVERNAME               1064
#define IDC_BTNIOLOAD                   1065
#define IDC_BTNIOSAVE                   1066
#define IDC_BTNIOREFRESH                1067
#define IDC_BTNIOAPPLY                  1068
#define IDC_BTNIONEW                    1069
#define IDC_TXTTOTALDESCRIPTORS         1070
#define IDC_TXTLISTENINGSOCKETS         1071
#define IDC_TXTTOTALCONNECTIONS         1072
#define IDC_TXTDATASENT                 1073
#define IDC_TXTDATARECIEVED             1074
#define IDC_EDITNETWORKNAME             1075
#define IDC_EDITSERVERNAME              1076
#define IDC_EDITSERVERDESC              1077
#define IDC_EDITLOC2                    1078
#define IDC_EDITADMINEMAIL              1079
#define IDC_LISTBINDINGS                1080
#define IDC_BTNADDBINDING               1081
#define IDC_CKUSEDNS                    1082
#define IDC_CKCACHEDNS                  1083
#define IDC_CKMASK                      1084
#define IDC_GRPMASK                     1085
#define IDC_BTNADDACCT                  1086
#define IDC_BTNMODACCT                  1087
#define IDC_BTNDELACCT                  1088
#define IDC_BTNEXCEPTIONOK              1089
#define IDC_BTNINBOUNDOK                1090
#define IDC_BTNREFRESHACCTS             1091
#define IDC_BTNDELBAN                   1092
#define IDC_BTNREFRESHBAN               1093
#define IDC_CKCDMMODERATED              1094
#define IDC_CKCDMNOEXTERN               1095
#define IDC_CKCDMONLYOPSSETTOPIC        1096
#define IDC_CKCDMKNOCK                  1097
#define IDC_CKCDMNOWHISPERS             1098
#define IDC_CKCDMLIMIT                  1099
#define IDC_EDITCDMLIMIT                1100
#define IDC_VSCDMLIMIT                  1101
#define IDC_BTNADDREGCHAN               1102
#define IDC_BTNMODREGCHAN               1103
#define IDC_BTNDELREGCHAN               1104
#define IDC_BTNREFRESHREGCHANS          1105
#define IDC_CKCCCREATEDYN               1106
#define IDC_CKCCJOINDYN                 1107
#define IDC_CKCCAUTOJOIN                1108
#define IDC_EDITCCAUTOJOIN              1109
#define IDC_LISTCCAUTOJOIN              1110
#define IDC_BTNCCAUTOJOIN1              1111
#define IDC_BTNCCAUTOJOIN2              1112
#define IDC_EDITCCMAXCHANS              1113
#define IDC_EDITUMUSERSPERIP            1114
#define IDC_VSUMUSERSPERIP              1115
#define IDC_EDITUMRECVQ                 1116
#define IDC_VSUMRECVQ                   1117
#define IDC_VSUMSENDQ                   1118
#define IDC_EDITPINGDURATION            1119
#define IDC_VSPINGDURATION              1120
#define IDC_EDITPINGRESPONSE            1121
#define IDC_CKNICKDELAY                 1122
#define IDC_VSNICKDELAY                 1123
#define IDC_CKMSGDELAY                  1124
#define IDC_BTNADDSERVER                1125
#define IDC_BTNMODSERVER                1126
#define IDC_BTNDELSERVER                1127
#define IDC_BTNREFRESHSERVERS           1128
#define IDC_CKCSNICKINCHAN              1129
#define IDC_EDITCSMAXACCESS             1130
#define IDC_GRPSPOOF                    1131
#define IDC_BTNSPOOF                    1132
#define IDC_EDITMAXMSGLEN               1133
#define IDC_EDITFILTERTOPIC             1134
#define IDC_BTNADDFILTER                1135
#define IDC_BTNMODFILTER                1136
#define IDC_EDITMAXCHANLEN              1137
#define IDC_BTNDELFILTER                1138
#define IDC_EDITMAXTOPICLEN             1139
#define IDC_BTNREFRESHFILTERS           1140
#define IDC_EDITFILTERALL               1141
#define IDC_BTNDELBINDING               1142
#define IDC_LISTFILTERCHAN              1143
#define IDC_LISTFILTERTOPIC             1144
#define IDC_RDMASK2                     1145
#define IDC_LVEXCEPTIONS                1146
#define IDC_CKSPOOF3128                 1147
#define IDC_VSPINGRESPONSE              1148
#define IDC_CKSPOOF8080                 1149
#define IDC_TXTSPOOFPUNISHMENT          1150
#define IDC_VSMAXCHANLEN                1151
#define IDC_VSMAXTOPICLEN               1152
#define IDC_VSMAXMSGLEN                 1153
#define IDC_EDITRAPORT                  1154
#define IDC_SPOOFPUNISHMENT             1155
#define IDC_TXTREGGLOBAL                1156
#define IDC_CKFILTERNICK                1157
#define IDC_GRPFILTERNICK               1158
#define IDC_CKFILTERCHAN                1159
#define IDC_GRPFILTERCHAN               1160
#define IDC_CKFILTERTOPIC               1161
#define IDC_EDITFILTERCANCEL            1162
#define IDC_BTNREGCHANMODACCESS         1163
#define IDC_BTNADDBAN                   1164
#define IDC_BTNREGCHANDELACCESS         1165
#define IDC_BTNMODBAN                   1166
#define IDC_CBBANSCOPE                  1167
#define IDC_EDITBANEXPIRATION           1168
#define IDC_CBBANEXPIRATION             1169
#define IDC_BTNREGCHANREFRESHACCESS     1170
#define IDC_GRPFILTERTOPIC              1171
#define IDC_CKBANREASON                 1172
#define IDC_TXTNOTE                     1173
#define IDC_CKBANEXPIRATION             1174
#define IDC_TXTFILTERALL                1175
#define IDC_EDITBANHOSTMASK             1176
#define IDC_BTNFILTERCANCEL             1177
#define IDC_EDITBANREASON               1178
#define IDC_CBSPOOFPUNISHMENT           1179
#define IDC_BTNBANOK                    1180
#define IDC_VSCACHEDNS                  1181
#define IDC_BTNBANCANCEL                1182
#define IDC_LVDETECTEDHOSTS             1185
#define IDC_BTNDETECTEDHOSTSOK          1186
#define IDC_BTNDETECTEDHOSTSCANCEL      1187
#define IDC_BTNREPORTCOPY               1188
#define IDC_EDITBINDIPADDR              1189
#define IDC_EDITEXCEPTIONHOSTMASK       1190
#define IDC_EDITBINDPORT                1191
#define IDC_EDITDETAILSSERVER           1192
#define IDC_EDITDETAILSPORT             1193
#define IDC_TXTDETAILSTOTAL             1194
#define IDC_RDEXPORTONEFILE             1195
#define IDC_RDEXPORTMULTIFILES          1196
#define IDC_EDITEXPORTFOLDER            1197
#define IDC_BTNEXPORTFOLDER             1198
#define IDC_BTNEXPORTOK                 1199
#define IDC_BTNEXPORTCANCEL             1200
#define IDC_EDITREPORT                  1201
#define IDC_BTNEXCEPTIONCANCEL          1202
#define IDC_BTNBINDOK                   1203
#define IDC_BTNREGCHANCANCEL            1204
#define IDC_EDITINBOUNDNAME             1205
#define IDC_EDITREGCHANTOPIC            1206
#define IDC_EDITREGCHANONJOIN           1207
#define IDC_EDITREGCHANONPART           1208
#define IDC_EDITREGCHANNAME             1209
#define IDC_LVREGCHANACCESS             1210
#define IDC_BTNREGCHANADDACCESS         1211
#define IDC_EDITREGCHANMEMBERKEY        1212
#define IDC_CBREGCHANMODEVISIBILITY     1213
#define IDC_CKREGCHANMODEL              1214
#define IDC_VSREGCHANMODEL              1215
#define IDC_CKREGCHANMODEA              1216
#define IDC_CKREGCHANMODEM              1217
#define IDC_CKREGCHANMODET              1218
#define IDC_CKREGCHANMODEW              1219
#define IDC_CKREGCHANMODEI              1220
#define IDC_CKREGCHANMODEN              1221
#define IDC_CKREGCHANMODEU              1222
#define IDC_CKREGCHANMODEX              1223
#define IDC_EDITACCESSEXPIRE            1224
#define IDC_CBACCESSEXPIRE              1225
#define IDC_EDITACCESSHOSTMASK          1226
#define IDC_CBACCESSTYPE                1227
#define IDC_CKACCESSEXPIRE              1228
#define IDC_BTNACCESSOK                 1229
#define IDC_BTNACCESSCANCEL             1230
#define IDC_EDITREGCHANMODEL            1231
#define IDC_BTNDETECTEDHOSTSVIEW        1232
#define IDC_BTNDETECTEDHOSTSEXPORT      1233
#define IDC_CKACCESSREASON              1234
#define IDC_EDITINBOUNDHOSTNAME         1235
#define IDC_BTNBINDCANCEL               1236
#define IDC_EDITINBOUNDPASSWORD         1237
#define IDC_EDITINBOUNDPINGFREQUENCY    1238
#define IDC_GRPREPORT                   1239
#define IDC_EDITOUTBOUNDPORT            1239
#define IDC_VSBINDPORT                  1240
#define IDC_EDITLOCALUSERS              1241
#define IDC_EDITLOCALUSERSMAX           1243
#define IDC_EDITCONNECTHOSTNAME         1244
#define IDC_CBACCTLEVEL                 1245
#define IDC_EDITGLOBALUSERS             1246
#define IDC_EDITCONNECTPORT             1247
#define IDC_LVOUTBOUND                  1248
#define IDC_VSRAPORT                    1249
#define IDC_BTNDETAILSREPORT            1250
#define IDC_BTNRAPASSWORD               1251
#define IDC_BTNREPORTCLOSE              1252
#define IDC_BTNPASSWORDOK               1253
#define IDC_LISTDETAILSLOGINS           1254
#define IDC_BTNDETECTEDHOSTSDELETE      1255
#define IDC_EDITDETAILSHOSTMASK         1256
#define IDC_CBNETWORKTYPE               1257
#define IDC_CBSERVERENCRYPTION          1258
#define IDC_TXTOUTBOUNDPORT             1259
#define IDC_EDITREGCHANHOSTKEY          1260
#define IDC_EDITACCESSREASON            1261
#define IDC_TABREGCHAN                  1262
#define IDC_BTNREGCHANOK                1263
#define IDC_EDITREGCHANOWNERKEY         1264
#define IDC_VSINBOUNDPINGFREQUENCY      1265
#define IDC_EDITACCTHOSTMASK            1266
#define IDC_VSOUTBOUNDPORT              1266
#define IDC_EDITINBOUNDPINGRESPONSE     1267
#define IDC_EDITACCTPASSWORD            1268
#define IDC_SCROLLBAR2                  1269
#define IDC_VSINBOUNDPINGRESPONSE       1270
#define IDC_EDITOUTBOUNDPASS            1271
#define IDC_BTNDETECTEDHOSTSCLEAR       1273
#define IDC_EDITDETAILSSPOOFEDPORTS     1274
#define IDC_BTNINBOUNDCANCEL            1275
#define IDC_EDITGLOBALUSERSMAX          1276
#define IDC_VSCONNECTPORT               1277
#define IDC_BTNACCTOK                   1278
#define IDC_EDITCONNECTPASSWORD         1279
#define IDC_BTNCONNECT                  1281
#define IDC_BUTTON3                     1282
#define IDC_BTNCONNECTCLOSE             1283
#define IDC_PROGRESS1                   1285
#define IDC_BTNACCTCANCEL               1286
#define IDC_BTNPASSWORDCANCEL           1287
#define IDC_EDITPASSWORDOLD             1289
#define IDC_BTNDETAILSCLOSE             1290
#define IDC_EDITPASSWORDNEW             1291
#define IDC_BTNREPORTSAVEAS             1292
#define IDC_EDIT3                       1293
#define IDC_EDITPASSWORDNEW2            1294
#define IDC_CKSPOOF3182                 1295
#define IDC_LISTREPORT                  1296
#define IDC_EDIT1                       1297
#define IDC_EDITSERVERID                1298
#define IDC_RDSERVERINBOUND             1299
#define IDC_RDSERVEROUTBOUND            1300
#define IDC_COMBO1                      1301
#define IDC_TAB1                        1302
#define IDC_EDITREGCHANSUBJECT          1303
#define IDC_TXTPINGFREQUENCY            1304

#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1261
#define _APS_NEXT_SYMED_VALUE           275
#endif
#endif
